project:
  type: website

website:
  title: "Introducción al procesamiento, visualización y análisis de datos espaciales en R"
  twitter-card: 
    creator: "@dlizcano"
    site: "https://github.com/dlizcano/spatialdata_lite"
  site-url: "https://dlizcano.github.io/spatialdata_lite"
  repo-url: "https://github.com/dlizcano/spatialdata_lite"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: AM.qmd
        text: AM
      - href: PM.qmd
        text: PM
      - href: about.qmd
      - text: about
      - icon: github
        href: https://github.com/dlizcano/spatialdata_lite
        aria-label: GitHub

format:
  html:
    theme: 
      light: Flatly
      dark: darkly
    css: styles.css
    toc: true

    
editor: visual

